### ISSUE TITLE
Any detailed schedule to release code?

### ISSUE THREAD

**Issue by wjc2830** [hustvl/ControlAR#1]
Hi, there. Thanks for contributing an interesting work. I am wondering do you have any detailed plans about open source. Before ICLR or after?

**Comment by wondervictor** [comment]
Hi @wjc2830, we are going to release the full code around 1 week as we need to go through the company's review process.

**Comment by wjc2830** [comment]
Cool! Thanks for your prompt reply.

**Comment by wondervictor** [comment]
Hi @wjc2830, we have released the complete code and models of ControlAR.
